using System.Text;

namespace BunnyGarden2FixMod.ConfigGen;

public static class CodeEmitter
{
    public static string Emit(List<ConfigEntryDef> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   This file is generated by ConfigGen. Do not edit manually.");
        sb.AppendLine("//   Source: Configs.yaml");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable disable");
        sb.AppendLine("using BepInEx.Configuration;");
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("namespace BunnyGarden2FixMod;");
        sb.AppendLine();
        sb.AppendLine("public static class Configs");
        sb.AppendLine("{");

        EmitFields(sb, entries);
        EmitBindAll(sb, entries);
        EmitUIEntries(sb, entries);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitFields(StringBuilder sb, List<ConfigEntryDef> entries)
    {
        sb.AppendLine("    // ─── 静的フィールド ──────────────────────────────");
        foreach (var e in entries)
        {
            sb.AppendLine($"    /// <summary>{XmlEscape(e.Label)}</summary>");
            if (e.Type == "hotkey")
            {
                sb.AppendLine($"    public static global::BunnyGarden2FixMod.Utils.HotkeyConfig {e.Name};");
            }
            else
            {
                var csType = MapType(e);
                sb.AppendLine($"    public static ConfigEntry<{csType}> {e.Name};");
            }
        }
        sb.AppendLine();
    }

    private static void EmitBindAll(StringBuilder sb, List<ConfigEntryDef> entries)
    {
        sb.AppendLine("    // ─── BindAll: Plugin.Awake から1回呼ぶ ──────────");
        sb.AppendLine("    public static void BindAll(ConfigFile cfg)");
        sb.AppendLine("    {");
        foreach (var e in entries)
        {
            if (e.Type == "hotkey")
            {
                EmitHotkeyBind(sb, e);
                sb.AppendLine();
                continue;
            }

            var csType = MapType(e);
            var defaultLit = FormatDefault(e);
            var descLit = ToVerbatimStringLiteral(BuildDescriptionWithLabel(e));

            if (e.Range != null && e.Range.Count == 2)
            {
                var minLit = FormatNumeric(e.Range[0], e.Type);
                var maxLit = FormatNumeric(e.Range[1], e.Type);
                sb.AppendLine($"        {e.Name} = cfg.Bind(\"{e.Section}\", \"{e.EffectiveKey}\",");
                sb.AppendLine($"            {defaultLit},");
                sb.AppendLine($"            new ConfigDescription(");
                sb.AppendLine($"                {descLit},");
                sb.AppendLine($"                new AcceptableValueRange<{csType}>({minLit}, {maxLit})));");
            }
            else
            {
                sb.AppendLine($"        {e.Name} = cfg.Bind(\"{e.Section}\", \"{e.EffectiveKey}\",");
                sb.AppendLine($"            {defaultLit},");
                sb.AppendLine($"            {descLit});");
            }
            sb.AppendLine();
        }
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitHotkeyBind(StringBuilder sb, ConfigEntryDef e)
    {
        if (string.IsNullOrEmpty(e.DefaultKey))
            throw new InvalidOperationException($"[{e.Name}] type=hotkey requires defaultKey");
        var labelLit = ToVerbatimStringLiteral(e.Label ?? string.Empty);
        var descLit = ToVerbatimStringLiteral((e.Description ?? string.Empty).TrimEnd('\n'));
        var button = string.IsNullOrEmpty(e.DefaultButton) ? "None" : e.DefaultButton!;
        sb.AppendLine($"        {e.Name} = new global::BunnyGarden2FixMod.Utils.HotkeyConfig(cfg,");
        sb.AppendLine($"            \"{e.Section}\", \"{e.EffectiveKey}\",");
        sb.AppendLine($"            global::UnityEngine.InputSystem.Key.{e.DefaultKey},");
        sb.AppendLine($"            global::BunnyGarden2FixMod.Utils.ControllerButton.{button},");
        sb.AppendLine($"            {labelLit},");
        if (!string.IsNullOrEmpty(e.ControllerDescription))
        {
            var ctrlDescLit = ToVerbatimStringLiteral(e.ControllerDescription!.TrimEnd('\n'));
            sb.AppendLine($"            {descLit},");
            sb.AppendLine($"            {ctrlDescLit});");
        }
        else
        {
            sb.AppendLine($"            {descLit});");
        }
    }

    private static void EmitUIEntries(StringBuilder sb, List<ConfigEntryDef> entries)
    {
        sb.AppendLine("    // ─── UIEntries: F9 設定パネルが foreach で描画する ──");
        sb.AppendLine("    public static System.Collections.Generic.IReadOnlyList<global::BunnyGarden2FixMod.Patches.Settings.UIEntryMeta> UIEntries { get; } = new global::BunnyGarden2FixMod.Patches.Settings.UIEntryMeta[]");
        sb.AppendLine("    {");

        foreach (var e in entries)
        {
            if (e.Ui == null) continue;
            EmitOneUIEntry(sb, e);
        }

        sb.AppendLine("    };");
        sb.AppendLine();
    }

    private static void EmitOneUIEntry(StringBuilder sb, ConfigEntryDef e)
    {
        var labelLit = ToCSharpStringLiteral(e.Label);
        var categoryLit = ToCSharpStringLiteral(e.Section);

        sb.AppendLine("        new global::BunnyGarden2FixMod.Patches.Settings.UIEntryMeta");
        sb.AppendLine("        {");
        var descLit = ToCSharpStringLiteral(e.Description ?? string.Empty);
        sb.AppendLine($"            Category = {categoryLit},");
        sb.AppendLine($"            Label    = {labelLit},");
        sb.AppendLine($"            Desc     = {descLit},");
        if (!string.IsNullOrEmpty(e.Group))
            sb.AppendLine($"            Group    = {ToCSharpStringLiteral(e.Group)},");

        if (e.Ui!.Kind == "toggle")
        {
            sb.AppendLine("            Kind     = global::BunnyGarden2FixMod.Patches.Settings.UIKind.Toggle,");
            sb.AppendLine($"            Accessor = new global::BunnyGarden2FixMod.Patches.Settings.BoolAccessor(() => {e.Name}),");
        }
        else if (e.Ui.Kind == "dropdown")
        {
            // enum メンバ列挙はランタイムで Enum.GetNames を呼ぶ。
            // EnumAccessor<T> 内の Enum.GetValues と同一順序が保証されるため index ズレが起きない。
            var enumType = e.EnumType!;
            sb.AppendLine("            Kind            = global::BunnyGarden2FixMod.Patches.Settings.UIKind.Dropdown,");
            sb.AppendLine($"            DropdownOptions = global::System.Enum.GetNames(typeof(global::{enumType})),");
            sb.AppendLine($"            Accessor        = new global::BunnyGarden2FixMod.Patches.Settings.EnumAccessor<global::{enumType}>(() => {e.Name}),");
        }
        else if (e.Ui.Kind == "keybinding")
        {
            // hotkey 専用: HotkeyProvider 経由で KeyConfig / ButtonConfig に直接アクセス。
            // DropdownOptions は Pad ボタン側で使う (ControllerButton 列挙)。
            // Accessor は KeyBinding 行では未使用 (null のまま)。
            sb.AppendLine("            Kind            = global::BunnyGarden2FixMod.Patches.Settings.UIKind.KeyBinding,");
            sb.AppendLine($"            HotkeyProvider  = () => {e.Name},");
            sb.AppendLine("            DropdownOptions = global::System.Enum.GetNames(typeof(global::BunnyGarden2FixMod.Utils.ControllerButton)),");
        }
        else // slider
        {
            var min = FormatNumberInvariant(e.Range![0]);
            var max = FormatNumberInvariant(e.Range[1]);
            var step = e.Ui.Step!.Value.ToString("R", System.Globalization.CultureInfo.InvariantCulture);
            var formatLit = ToCSharpStringLiteral(e.Ui.Format!);

            sb.AppendLine("            Kind       = global::BunnyGarden2FixMod.Patches.Settings.UIKind.Slider,");
            sb.AppendLine($"            SliderMin  = {min}f,");
            sb.AppendLine($"            SliderMax  = {max}f,");
            sb.AppendLine($"            SliderStep = {step}f,");
            sb.AppendLine($"            Format     = {formatLit},");

            if (e.Type == "int")
            {
                sb.AppendLine($"            Accessor = new global::BunnyGarden2FixMod.Patches.Settings.IntAccessor(() => {e.Name}, {step}f),");
            }
            else // float
            {
                sb.AppendLine($"            Accessor = new global::BunnyGarden2FixMod.Patches.Settings.FloatAccessor(() => {e.Name}, {step}f),");
            }
        }

        sb.AppendLine("        },");
    }

    private static string ToCSharpStringLiteral(string s)
    {
        var escaped = s
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r", "\\r")
            .Replace("\n", "\\n");
        return $"\"{escaped}\"";
    }

    private static string FormatNumberInvariant(object v)
    {
        return System.Convert.ToDouble(v, System.Globalization.CultureInfo.InvariantCulture)
            .ToString("R", System.Globalization.CultureInfo.InvariantCulture);
    }

    public static string MapType(ConfigEntryDef e) => e.Type switch
    {
        "bool"  => "bool",
        "int"   => "int",
        "float" => "float",
        "enum"  => e.EnumType ?? throw new InvalidOperationException($"[{e.Name}] enumType required"),
        "key"   => e.EnumType ?? throw new InvalidOperationException($"[{e.Name}] enumType required"),
        _ => throw new InvalidOperationException($"[{e.Name}] unknown type: {e.Type}")
    };

    private static string FormatDefault(ConfigEntryDef e)
    {
        if (e.Default == null) throw new InvalidOperationException($"[{e.Name}] default is required");
        return e.Type switch
        {
            // YAML が `default: false` でも `default: "False"` でも常に正規化された
            // 'true'/'false' を出力するため、一度 bool.Parse を通してから小文字化する。
            "bool"  => bool.Parse(e.Default.ToString()!).ToString().ToLowerInvariant(),
            "int"   => e.Default.ToString()!,
            "float" => $"{Convert.ToSingle(e.Default, System.Globalization.CultureInfo.InvariantCulture)
                            .ToString("0.0##############", System.Globalization.CultureInfo.InvariantCulture)}f",
            "enum"  => $"{e.EnumType}.{e.Default}",
            "key"   => $"{e.EnumType}.{e.Default}",
            _ => throw new InvalidOperationException($"[{e.Name}] unknown type")
        };
    }

    private static string FormatNumeric(object v, string type) => type switch
    {
        "int"   => v.ToString()!,
        "float" => $"{Convert.ToSingle(v, System.Globalization.CultureInfo.InvariantCulture)
                        .ToString("0.0##############", System.Globalization.CultureInfo.InvariantCulture)}f",
        _ => v.ToString()!
    };

    /// <summary>
    /// ConfigDescription の本文を組み立てる: 1 行目を label、2 行目以降を YAML description とする。
    /// BepInEx は .cfg ファイルに改行を保持するため、ユーザーは label を「設定の見出し」として読める。
    /// description が空ならば label のみ。
    /// </summary>
    private static string BuildDescriptionWithLabel(ConfigEntryDef e)
    {
        // Validator が label を必須化しているが、ヘルパー単体での安全性のため null も吸収する。
        var label = e.Label ?? string.Empty;
        var desc = (e.Description ?? string.Empty).TrimEnd('\n');
        if (string.IsNullOrEmpty(desc)) return label;
        return label + "\n" + desc;
    }

    private static string ToVerbatimStringLiteral(string s)
    {
        return "@\"" + s.Replace("\"", "\"\"") + "\"";
    }

    private static string XmlEscape(string s)
    {
        return s
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");
    }
}
